name: Build production docker image and deploy to azure container
concurrency: wherewego-production

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BRANCH: main
  PROJECT_ENV: production
  TAG_PREFIX: v

jobs:
  tag_and_build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#deployonly')"
    env:
      REPO: wherewego_landing_prod
      DOCKERFILE: ./deployment/Dockerfile
      ENCODED_ENV_KEY: LANDING_WHEREWEGO_PROD

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0

      - name: Git Version
        id: semvar
        uses: paulhatch/semantic-version@v5.0.3
        with:
          tag_prefix: "${{ env.TAG_PREFIX }}"
          version_format: "${major}.${minor}.${patch}"

      - name: Tag main branch with latest version
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: "${{ steps.semvar.outputs.version_tag }}"

      - name: Decode and write env file
        id: write_env
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: '.env'
          fileDir: './gno-inc/'
          encodedString: ${{ secrets[env.ENCODED_ENV_KEY] }}

      - name: 'Replace variables in update_ip script'
        uses: cschleiden/replace-tokens@v1
        with:
          files: "deployment/update_ip.sh"
        env:
          IP_KEY: ${{ secrets.IP_KEY }}

      - name: Build and push image to registry
        uses: nikkag/build-docker-push-azure-action@main
        with:
          acr_username: ${{ secrets.ACR_TOKEN_NAME }}
          acr_password: ${{ secrets.ACR_TOKEN_VALUE }}
          registry: wherewego
          repo: ${{ env.REPO }}
          dockerfile: ${{ env.DOCKERFILE }}
          version_tag: ${{ steps.semvar.outputs.version_tag }}
          build_args: |
            PROJECT_ENV=${{ env.PROJECT_ENV }}

  deploy_group:
    runs-on: ubuntu-latest
    needs: tag_and_build
    if: always()
    env:
      DEPLOY_FILE: deployment/deploy-azure-fe-production.yaml

    steps:
      - name: Fail if needed jobs fail without deployonly tag
        if: ${{ contains(needs.*.result, 'failure') && !contains(github.event.head_commit.message, '#deployonly')}}
        run: exit 1

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0

      - name: 'Get Latest tag'
        id: tag
        run: |
          TAG=$(git describe --abbrev=0 --match "${{ env.TAG_PREFIX }}*")
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Replace variables in deployment script'
        uses: cschleiden/replace-tokens@v1
        with:
          files: "${{ env.DEPLOY_FILE }}"
        env:
          LND_VERSION: ${{ steps.tag.outputs.tag }}
          ACR_TOKEN_NAME: ${{ secrets.ACR_TOKEN_NAME }}
          ACR_TOKEN_VALUE: ${{ secrets.ACR_TOKEN_VALUE }}
          LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

      - name: Deploy to Azure Container Instances
        run: az container create -g wwg --file ${{ env.DEPLOY_FILE }}

      - name: Purge old images from registry
        run: az acr run -g wwg --cmd "${{ env.purge_cmd }}" --registry wherewego  --timeout 360 /dev/null
        env:
          purge_cmd: "acr purge --filter 'wherewego_landing_prod:v.*' --ago 0d --keep 2 --untagged"
